config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homepage#index"
  get "groups", to: "groups#index"
  post "groups", to: "groups#create"
  delete "groups", to: "groups#destroy"
  patch "group/:id", to: "groups#update"
  post "join_group", to: "groups#request_to_join"
  post "update_request", to: "groups#approve_or_reject_request"
  post "remove_member", to: "groups#remove_member"
  get "group/:uuid", to: "groups#show", as: "group"
  get "health_check", to: "homepage#health_check"
  resources :posts
  resources :comments
  resources :images, only: [:create]
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: {minimum: 6, maximum: 100}
  validates :uuid, presence: true
  validates :access_level, inclusion: {in: ["public", "private", "secret"]}
  validates :owner_id, presence: true

  has_many :group_members, class_name: "GroupMember", dependent: :destroy
  has_many :users, through: :group_members
  has_many :joining_requests, -> { where status: "pending" }

  belongs_to :owner, class_name: "User", foreign_key: "owner_id"

  has_many :posts, dependent: :destroy

  scope :all_groups, ->(user_id) { joins(:group_members).where("group_members.user_id" => user_id).or(where.not("access_level" => "secret")) }

  def update_last_activity
    update_column(:last_activity, DateTime.now)
  end
end

app/controllers/api/groups_controller.rb
class Api::GroupsController < ApplicationController
    before_action :set_group, only: [:show, :update, :destroy]

    def index

        user = current_user
        
        groups = Group.left_outer_joins(:users)

        type = params[:type]
        if type == 'owner'
            groups = groups.where(owner_id: user.id)
        elsif type == 'member'
            groups = user.groups
        end

        @groups = groups.where.not(access_level: 'secret').paginate(page: params[:page], per_page: 15)
    end

    def show
    end

    def create
        @group = Group.new(group_params)

        @group.uuid = SecureRandom.uuid

        if @group.save
            render 'api/groups/show'
        else
            render json: { status: false, message: 'Unable to create group', errors: @group.errors.full_messages }
        end
    end

    def update
        if @group.update(group_params)
            render 'api/groups/show'
        else
            render json: { status: false, message: 'Unable to update group', errors: @group.errors.full_messages }
        end
    end

    def destroy
        @group.destroy
        render json: { status: true, message: 'Group Deleted!' }
    end

    def request_to_join
        group = Group.find(params[:group_id]);
        if(group.access_level == 'public')
            GroupMember.new(group_id: params[:group_id], user_id: params[:user_id], joining_date: DateTime.now)
        else
            JoiningRequest.new(group_id: params[:group_id], user_id: params[:user_id], status: 'pending')
        end
        render json: { status: true, message: 'Your request has been submitted!' }
    end

    def approve_or_reject_request
        request = JoiningRequest.find(params[:request_id]);
        if params[:status] == true
            GroupMember.new(group_id: request.group_id, user_id: request.user_id, joining_date: DateTime.now)
            request.status = 'approved'
            request.save
        else
            request.status = 'rejected'
        end
        render json: { status: true, message: 'Request Updated!' }
    end

    def remove_member
        member = GroupMember.find(params[:membership_id]);
        member.destroy
        render json: { status: true, message: 'Memeber Removed from group!' }
    end

    private 

    def set_group
        @group = Group.find_by(uuid: params[:uuid])
    end

    def group_params
        params.require(:group).permit(:name, :access_level, :owner_id)
    end

end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
    before_action :set_group, only: [:show, :update, :destroy]

    def index
        groups = Group.paginate(page: params[:page], per_page: 15)
        render json: { status: true, data: groups }
    end

    def show
        render json: { status: true, data: @group }
    end

    def create
        group = Group.new(group_params)
        if group.access_level == "secret"
            group.invitation_link = SecureRandom.alphanumeric(32);
        end
        if group.save
            render json: { status: true, message: 'Group created!', data: group }
            
        else
            render json: { status: false, message: 'Unable to create group', errors: group.errros.full_messages }
        end
    end

    def update
        if @group.update(group_params)
            render json: { status: true, message: 'Group Updated!', data: @group }
        else
            render json: { status: false, message: 'Unable to update group', errors: @group.errros.full_messages }
        end
    end

    def destroy
        @group.destroy
        render json: { status: true, message: 'Group Deleted!' }
    end

    def request_to_join
        group = Group.find(params[:group_id]);
        if(group.access_level == 'public')
            GroupMember.new(group_id: params[:group_id], user_id: params[:user_id], joining_date: DateTime.now)
        else
            JoiningRequest.new(group_id: params[:group_id], user_id: params[:user_id], status: 'pending')
        end
        render json: { status: true, message: 'Your request has been submitted!' }
    end

    def approve_or_reject_request
        request = JoiningRequest.find(params[:request_id]);
        if params[:status] == true
            GroupMember.new(group_id: request.group_id, user_id: request.user_id, joining_date: DateTime.now)
            request.status = 'approved'
            request.save
        else
            request.status = 'rejected'
        end
        render json: { status: true, message: 'Request Updated!' }
    end

    def remove_member
        member = GroupMember.find(params[:membership_id]);
        member.destroy
        render json: { status: true, message: 'Memeber Removed from group!' }
    end

    private 

    def set_group
        @group = Group.find(params[:id])
    end

    def group_params
        params.require(:group).permit(:name, :access_level, :owner_id)
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    groups = Group
    type = params[:type]
    groups = if type == "owner"
      groups.where(owner_id: current_user.id)
    elsif type == "member"
      current_user.groups
    else
      groups.distinct.all_groups(current_user.id)
    end
    @groups = groups.paginate(page: params[:page], per_page: 15)
  end

  def show
    @is_admin = current_user.id == @group.owner_id
    @is_member = @is_admin || GroupMember.find_by(user_id: current_user.id, group_id: @group.id) ? true : false
    if !@is_member
      render "join_group"
    end
    @post = Post.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.uuid = SecureRandom.uuid
    if @group.save
      GroupMember.create(group_id: @group.id, user_id: current_user.id, joining_date: DateTime.now)
      redirect_to groups_path
    else
      redirect_back fallback_location: groups_path, flash: {errors: @group.errors.full_messages}
    end
  end

  def update
    errors = []

    @group = Group.find(params[:id])
    if !@group.update(group_params)
      errors = @group.errors.full_messages
      render json: {status: false, message: "Unable to update group", errors: @group.errors.full_messages}
    end
    redirect_back fallback_location: group_path(uuid: @group.uuid), flash: {errors: errors}
  end

  def destroy
    @group.destroy
    redirect_back fallback_location: groups_path
  end

  def request_to_join
    group = Group.find(params[:group_id])
    if group.access_level == "public"
      GroupMember.create(group_id: params[:group_id], user_id: params[:user_id], joining_date: DateTime.now)
    else
      JoiningRequest.create(group_id: params[:group_id], user_id: params[:user_id], status: "pending")
    end
    redirect_back fallback_location: groups_path
  end

  def approve_or_reject_request
    request = JoiningRequest.find(params[:request_id])
    if to_boolean(params[:status]) == true
      GroupMember.create(group_id: request.group_id, user_id: request.user_id, joining_date: DateTime.now)
      request.status = "approved"
    else
      request.status = "rejected"
    end
    request.save
    redirect_back fallback_location: group_path(uuid: request.group.uuid)
  end

  def remove_member
    member = GroupMember.find(params[:membership_id])
    member.destroy
    redirect_back fallback_location: group_path(uuid: member.group.uuid)
  end

  private

  def set_group
    @group = Group.find_by(uuid: params[:uuid])
  end

  def group_params
    params.require(:group).permit(:name, :access_level)
  end

  def to_boolean(str)
    str.downcase == "true"
  end
end

app/views/groups/index.html.erb
<div class='container mx-auto mt-6 pt-6'>
  <% if flash[:errors] %>
    <%= render 'shared/errors', errors: flash[:errors] %>
  <% end %>
  <h1 class='text-3xl mb-8'>Groups</h1>
  <div class='flex justify-between'>
    <%= render(Tabs::SimpleTabsComponent.new(tabs: ["All Groups", "Created by me", "Where I am member"], keys: ['all', 'owner', 'member'], active_key: params[:type] || 'all', on_change: groups_path))%>
    <div data-controller="modal">
      <%= render(Buttons::PrimaryButtonComponent.new(title: "Create a new group", action: "click->modal#toggle", classes: 'w-52 rounded')) %>
      <%= render(Modals::GroupModalComponent.new(edit: false, group: Group.new, hanlde_submit: nil, on_hide: "click->modal#toggle"))%>
    </div>
  </div>
  <% @groups.each do |group|%>
    <%= render(Cards::GroupListingCardComponent.new(group: group, current_user: @current_user))%>
  <% end %>
</div>

app/views/groups/join_group.html.erb
<div class="accept-invitation">
  <%= render(Cards::GroupListingCardComponent.new(group: @group, current_user: @current_user))%>
</div>

app/views/groups/show.html.erb
<div class='container mx-auto mt-6'>
  <div class='inline-block w-2/3 align-top'>
    <div data-controller="modal">
      <%= link_to "<i class='fa-solid fa-arrow-left-long fa-2x'></i>".html_safe, groups_path, title: "Back to Groups" %>
      <h1 class='text-3xl mb-8 mt-2'><%= @group.name %> <% if @is_admin %> <i class="fa-solid fa-gear ml-5 cursor-pointer" data-action="click->modal#toggle"><% end %></i></h1>
      <%= render(Modals::GroupModalComponent.new(edit: true, group: @group, hanlde_submit: nil, on_hide: "click->modal#toggle")) if @is_admin %>
    </div>
    <% if @is_admin %>
      <div data-controller="invitation" >
        <input data-invitation-target="inviteLink" value="<%= request.original_url %>" hidden/>
        <p 
        data-action="click->invitation#copyLink" 
          class="mb-4 invitation-link">Copy Invitation Link <small data-invitation-target="linkMsg"></small></p>
      </div>
    <% end %>
    <%= render 'posts/form' %>
    <h1 class='text-3xl mb-8'>All Posts </h1>
    <% if @group.posts.present? %>
      <% @group.posts.each do |post|%>
        <%= render(Cards::PostListingCardComponent.new(post: post, current_user: @current_user, is_group_admin: @is_admin)) %>
      <% end %>
    <% else %>
      <h3 class="text-center bg-gray-100 p-5 mb-2">Wao :) Such an empty! </h3>
    <% end %>
  </div>
  <div class='inline-block w-1/4 align-top'>
    <div class='ml-9'>
      <div class='mb-4'>
        <% if @group.group_members.any? %>
          <h2 class='text-xl mb-4'>Members</h2>
          <div class='text-sm'>
            <% @group.group_members.each do |member|%>
              <div class="flex justify-between mb-4">
                <p><%= member.user.name %></p>
                <%= render(Buttons::IconButtonComponent.new(title: "Remove", icon: "fa-solid fa-xmark fa-2x text-danger", action_url: remove_member_path(membership_id: member.id, status: false))) if @is_admin && member.user.id != @group.owner_id %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class='mb-4'>
        <% if @is_admin && @group.joining_requests.any? %>
          <h2 class='text-xl mb-4 text-2xl'>Requests</h2>
          <div class='text-sm'>
            <% @group.joining_requests.each do |request|%>
              <div class="flex justify-between mb-4">
                <p class="text-lg w-36"><%= request.user.name %></p>
                <%= render(Buttons::IconButtonComponent.new(title: "Approve", icon: "fa-solid fa-check fa-2x text-success", action_url: update_request_path(request_id: request.id, status: true))) %>
                <%= render(Buttons::IconButtonComponent.new(title: "Reject", icon: "fa-solid fa-xmark fa-2x text-danger", action_url: update_request_path(request_id: request.id, status: false))) %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>