config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homepage#index"
  get "groups", to: "groups#index"
  post "groups", to: "groups#create"
  delete "groups", to: "groups#destroy"
  patch "group/:id", to: "groups#update"
  post "join_group", to: "groups#request_to_join"
  post "update_request", to: "groups#approve_or_reject_request"
  post "remove_member", to: "groups#remove_member"
  get "group/:uuid", to: "groups#show", as: "group"
  get "health_check", to: "homepage#health_check"
  resources :posts
  resources :comments
  resources :images, only: [:create]
end

app/views/layouts/_navigation.html.erb
<nav class="bg-white px-2 sm:px-4 py-2.5 dark:bg-gray-900 w-full z-20 border-b border-gray-200 dark:border-gray-600">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="<%= root_path %>" class="flex items-center">
      <img src="<%= asset_path('logo.png')%>" height="50px" width="70px" class="mr-3" alt="Take Home Logo">
      <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Take Home</span>
    </a>
    <div class="flex md:order-2">
      <% if user_signed_in? %>
        <%= render(Buttons::ActionButtonComponent.new(title: "Logout #{@current_user.name}", action_url: destroy_user_session_path, method: :delete, classes: "dark:text-white dark:border-white")) %>
      <% else %>
        <%= render(Links::ButtonLinkComponent.new(text:"Login", link: "/users/sign_in")) %>
      <% end %>
      <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      </button>
    </div>
    <% if user_signed_in? %>
    <div class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
      <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= link_to "Groups", groups_path, class: "block py-2 pr-4 pl-3 rounded text-black dark:text-white hover:underline"%>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Take Home</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/bd1eeb44c4.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js" integrity="sha512-/1nVu72YEESEbcmhE/EvjH/RxTg62EKvYWLG3NdeZibTCuEtW5M4z3aypcvsoZw03FAopi94y04GhuqRU9p+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css" integrity="sha512-5m1IeUDKtuFGvfgz32VVD0Jd/ySGX7xdLxhqemTmThxHdgqlgPdupWoSN8ThtUSLpAGBvA8DY2oO7jJCrGdxoA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/rp7s8uwi9knq4to990nnizr2i0ro0odzxe3fqdc4jyu2snpn/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <% if notice %>
      <div class="flex items-center bg-blue-500 text-white text-sm font-bold px-4 py-3" role="alert">
        <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if alert %>
      <div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3" role="alert">
        <p class="text-sm"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
    <div class="absolute top-28 right-0">
      <div id="notificationArea" class="inline-block w-3/3" data-controller="notification">
      </div>
    </div>
  </body>
</html>